export const TRANSACTION = "transaction"
export const INSERT = "INSERT"
export const UPDATE = "UPDATE"
export const DELETE = "DELETE"
export const UPDATE_INDEX = "UPDATE-INDEX"
export const UPDATE_LIST = "UPDATE-LIST"